#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$SCRIPT_DIR"
VENV_DIR="$PROJECT_ROOT/celestial_env"
REQUIREMENTS="$PROJECT_ROOT/requirements.txt"
CELESTIAL_DIR="$PROJECT_ROOT/celestial_watcher"
INDEX_DIR="$CELESTIAL_DIR/astrometry_indices"
CFG_PATH="$CELESTIAL_DIR/astrometry.cfg"

# astrometry.net's own recommended source for the 4100-series (Tycho-2, scales 7-19; "good for images wider than 1 degree" per data.astrometry.net)
INDEX_URL="http://data.astrometry.net/4100/"

echo "== Constellation Watcher setup =="
echo "Project root: $PROJECT_ROOT"
echo "Virtualenv: $VENV_DIR"
echo "Index directory:$INDEX_DIR"
echo "Config file: $CFG_PATH"
echo

# ------------------------------------------------------------------ #
# 1. Python virtual environment + pip dependencies
# ------------------------------------------------------------------ #
echo "-- Python environment --"
if [ -d "$VENV_DIR" ]; then
    echo "  [ok] $VENV_DIR already exists, reusing it"
else
    echo "  Creating virtual environment at $VENV_DIR ..."
    python3 -m venv "$VENV_DIR"
fi

PYTHON_BIN="$VENV_DIR/bin/python3"
PIP_BIN="$VENV_DIR/bin/pip"

"$PIP_BIN" install --upgrade pip

if [ -f "$REQUIREMENTS" ]; then
    echo "  Installing $REQUIREMENTS ..."
    "$PIP_BIN" install -r "$REQUIREMENTS"
else
    echo "  WARNING: $REQUIREMENTS not found, skipping pip install."
fi
echo

# ------------------------------------------------------------------ #
# 2. Check for solve-field (cannot be installed via pip -- see header)
# ------------------------------------------------------------------ #
echo "-- Checking for solve-field --"
if command -v solve-field >/dev/null 2>&1; then
    echo "  [ok] solve-field found: $(command -v solve-field)"
else
    cat <<'MSG'
  [missing] solve-field not found on PATH.

  This is the astrometry.net plate solver binary. It is not a Python
  package, so pip cannot install it. Install it with your system's package
  manager, then re-run this script (the rest of setup will still complete
  without it):

    Debian / Ubuntu / Raspberry Pi OS:
      sudo apt-get install astrometry.net

    macOS (Homebrew):
      brew install astrometry-net

    From source:
      https://astrometry.net/use.html
MSG
fi
echo

# ------------------------------------------------------------------ #
# 3. Download the 4100-series index files (stdlib Python, no wget/apt)
# ------------------------------------------------------------------ #
echo "-- Downloading astrometry.net 4100-series index files --"
echo "   (this is ~250 MB the first time; re-runs skip files already present)"
mkdir -p "$INDEX_DIR"

"$PYTHON_BIN" - "$INDEX_URL" "$INDEX_DIR" <<'PYEOF'
import re
import sys
import urllib.request

url, dest_dir = sys.argv[1], sys.argv[2]

with urllib.request.urlopen(url, timeout=60) as resp:
    html = resp.read().decode("utf-8", errors="replace")

# Apache-style directory listing: pull every href ending in .fits
names = sorted(set(re.findall(r'href="([^"?/]+\.fits)"', html)))
if not names:
    sys.exit(f"No .fits links found at {url} -- page format may have changed.")

downloaded = skipped = 0
for i, name in enumerate(names, 1):
    import os
    dest = os.path.join(dest_dir, name)
    if os.path.isfile(dest):
        skipped += 1
        continue
    print(f"  [{i}/{len(names)}] downloading {name} ...")
    urllib.request.urlretrieve(url.rstrip("/") + "/" + name, dest)
    downloaded += 1

print(f"Done: {downloaded} downloaded, {skipped} already present.")
PYEOF

echo "Index files present in $INDEX_DIR:"
ls -la "$INDEX_DIR"/*.fits 2>/dev/null || echo "  (none found -- download may have failed, check network access)"
echo

# ------------------------------------------------------------------ #
# 4. Generate astrometry.cfg pointing at the project-local index dir
# ------------------------------------------------------------------ #
echo "-- Writing astrometry.cfg --"
cat > "$CFG_PATH" <<EOF
# Generated by setup.bash. Do not hand-edit -- re-run setup.bash instead.
#
# add_path tells solve-field where to look for index files. autoindex means
# every .fits file found under that path is loaded automatically, so adding
# more index series later just means dropping files into $INDEX_DIR.
add_path $INDEX_DIR
autoindex
EOF

echo "Wrote:"
cat "$CFG_PATH"
echo

echo "== Setup complete =="
echo "To run the project:"
echo "  source $VENV_DIR/bin/activate"
echo "  python3 launch.py"